name: backend
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-server
    ports:
      - ${MINIO_API_PORT}:9000 # S3 API Port
      - ${MINIO_CONSOLE_PORT}:9001 # Web Console Port
    environment:
      - TZ=Asia/Bangkok
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server --console-address ":${MINIO_CONSOLE_PORT}" /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  minio_data: